### PR TITLE
API Request Optimization

### PR DESCRIPTION
**Pull request by EvanAgee**
Drying up API requests and moving them into our new modules, where appropriate.

### CODE REVIEW

**Comment by thadallender** [comment]
Nice work! I appreciate that you took the time to make variable names more semantic, and shore up the coding standards. A more concise codebase will definitely be easier to work with. Psyched!

With Expander Related enabled on settings, (which uses CartFieldRadio.vue component ), anywhere that the product selection form appears, three js errors are reported in the console:
 
1. The computed property "post" is already defined as a prop. found in ---> <CartFieldRadio> at src/components/parts/CartFieldRadio.vue
2. Error in render: "TypeError: Cannot read property 'downloads' of undefined" found in ---> <CartFieldRadio> at src/components/parts/CartFieldRadio.vue
3. TypeError: Cannot read property 'downloads' of undefined at VueComponent.getSizes

These are all probably related to a single issue. Are you seeing this?

**Comment by EvanAgee** [comment]
Thanks ! Yes, I should have mentioned that I didn't update anything in the Expander Related component, I probably misunderstood, but I thought that was a one-off for the project you were working on. Should I got ahead and update it as well?

**Comment by thadallender** [comment]
Yes, that would be great. I will test.

**Comment by EvanAgee** [comment]
Updated the Expander Related view, let me know if you see anything else that needs addressed.

**Comment by thadallender** [comment]
The individual attachment pages are not loading media or content. There is no JS error. Might be a problem with the API request for attachments?

**Comment by EvanAgee** [comment]
Cool, I’ll have a look

**Comment by EvanAgee** [comment]
Okay, pushed an update. Turns out that it was fetching the data but for whatever reason it was taking a while to return the result, so I added a loading state to both the search page and the item view.

**Comment by EvanAgee** [comment]
Let me know if we're looking good, thanks!

**Comment by thadallender** [comment]
Looks like the same is needed on src/components/pages/Attachment.vue also (gallery scenario). Is that working for you?

**Comment by EvanAgee** [comment]
I'll have a look

**Comment by EvanAgee** [comment]
Okay, pushed a fix with a few other small updates and also added a changelog!

**Comment by thadallender** [comment]
Three quick things:

1. On a product page, I get this js error:

`The computed property "attachment" is already defined in data.

found in

---> <Item> at src/components/pages/Item.vue
      <App> at src/components/Main.vue
        <Root>`

2. On a product attachment page, I get this js error:

`[Vue warn]: Error in created hook: "TypeError: Cannot read property 'sell' of undefined"

found in

---> <CartForm> at src/components/parts/CartForm.vue
       <Attachment> at src/components/pages/Attachment.vue
         <App> at src/components/Main.vue
           <Root>`

3. Looks like there is a console.log in Attachment.vue

**Pull request merged**
